name: partic
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audio_video_progress_bar: ^2.0.3
  spotify: ^0.13.7
  youtube_explode_dart: ^2.2.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/downloadfile.jpg"


flutter:
  uses-material-design: true
  assets:
    - assets/img/
